name: hakunapi

services:
  db:
    image: postgis/postgis:18-3.6
    restart: unless-stopped
    environment:
      POSTGRES_DB: address_fin
      POSTGRES_USER: address_reader
      POSTGRES_PASSWORD: test
    volumes:
      - ../examples/finnish_addresses/seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
      - ../examples/finnish_addresses/091.csv:/usr/local/share/091.csv:ro
      - ../examples/finnish_addresses/suomi_kunnat.csv:/usr/local/share/suomi_kunnat.csv:ro
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost" ]
      interval: 5s
      retries: 5
      timeout: 10s
  hakunapi:
    build:
      context: ../.
      dockerfile: Dockerfile-hotreload
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "41467:41467"
    volumes:
      # mount the working example config dir so hakunapi can read addresses.properties (read-only)
      - ./cfg:/app/config:ro
      - ../src:/app/java:ro
    environment:
      # Tell Tomcat / hakunapi where to find the config file and pass JVM flags to Tomcat
      CATALINA_OPTS: >-
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:41467
        -Dfeatures.hakuna.config.path=/app/config/addresses.properties
        -javaagent:"/opt/jbr/lib/hotswap/hotswap-agent.jar"
        -XX:HotswapAgent=external
        -XX:+AllowEnhancedClassRedefinition
        -XX:+ClassUnloading
        --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
        --add-opens=java.base/java.lang=ALL-UNNAMED
        --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
        --add-opens=java.base/java.io=ALL-UNNAMED
        --add-opens=java.base/sun.security.action=ALL-UNNAMED
        --add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED
        --add-opens=java.base/java.net=ALL-UNNAMED
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  db_data: {}
